// Voice style instructions for OpenAI TTS expressive voices
// Add or edit styles as needed

export const voiceStyles: Record<string, string> = {
  dramatic: "Voice Affect: Low, hushed, and suspenseful; convey tension and intrigue. Tone: Deeply serious and mysterious, maintaining an undercurrent of unease throughout. Pacing: Slow, deliberate, pausing slightly after suspenseful moments to heighten drama. Emotion: Restrained yet intense—voice should subtly tremble or tighten at key suspenseful points. Emphasis: Highlight sensory descriptions ('footsteps echoed,' 'heart hammering,' 'shadows melting into darkness') to amplify atmosphere. Pronunciation: Slightly elongated vowels and softened consonants for an eerie, haunting effect. Pauses: Insert meaningful pauses after phrases like 'only shadows melting into darkness,' and especially before the final line, to enhance suspense dramatically.",
  cowboy: "Voice: Warm, relaxed, and friendly, with a steady cowboy drawl that feels approachable. Punctuation: Light and natural, with gentle pauses that create a conversational rhythm without feeling rushed. Delivery: Smooth and easygoing, with a laid-back pace that reassures the listener while keeping things clear. Phrasing: Simple, direct, and folksy, using casual, familiar language to make technical support feel more personable. Tone: Light-hearted and welcoming, with a calm confidence that puts the caller at ease.",
  sympathetic: "Voice: Warm, empathetic, and professional, reassuring the customer that their issue is understood and will be resolved. Punctuation: Well-structured with natural pauses, allowing for clarity and a steady, calming flow. Delivery: Calm and patient, with a supportive and understanding tone that reassures the listener. Phrasing: Clear and concise, using customer-friendly language that avoids jargon while maintaining professionalism. Tone: Empathetic and solution-focused, emphasizing both understanding and proactive assistance.",
  sincere: "Voice Affect: Calm, composed, and reassuring; competent and in control, instilling trust. Tone: Sincere and empathetic, with genuine concern. Pacing: Slower during the apology for clarity, then slightly quicker when offering solutions to signal action. Emotions: Calm reassurance, empathy, and gratitude. Pronunciation: Clear and precise, emphasizing key words like 'refund' and 'patience'. Pauses: Before and after the apology to allow the listener to process.",
  "bedtime-story": "Affect: Gentle, curious narrator with a British accent, guiding a magical, child-friendly adventure. Tone: Magical, warm, and inviting, creating wonder and excitement. Pacing: Steady and measured, with slight pauses to emphasize magical moments. Emotion: Wonder, curiosity, and a sense of adventure. Pronunciation: Clear and precise, ensuring words are easy to follow and enchanting.",
  "eternal-optimist": "Voice: Warm, upbeat, and reassuring, with a steady, confident cadence. Tone: Positive and solution-oriented, focusing on next steps. Dialect: Neutral and professional, friendly and approachable. Pronunciation: Clear and precise, emphasizing key words to instill confidence. Features: Uses empathetic phrasing, gentle reassurance, and proactive language to shift focus from frustration to resolution.",
  "true-crime-buff": "Voice: Deep, hushed, and enigmatic, with a slow, deliberate cadence. Phrasing: Short, rhythmic sentences building tension with pauses. Punctuation: Dramatic pauses and abrupt stops enhance unease. Tone: Dark, ominous, and foreboding, evoking mystery and the unknown.",
  "sports-coach": "Voice Affect: Energetic and animated, with dynamic variations in pitch and tone. Tone: Excited and enthusiastic, conveying an upbeat atmosphere. Pacing: Rapid when describing key moments to convey intensity; slightly slower during dramatic pauses. Emotion: Intensely focused and excited, radiating positive energy. Pauses: Short, purposeful pauses after key moments.",
  auctioneer: "Voice: Staccato, fast-paced, energetic, and rhythmic, with the charm of a seasoned auctioneer. Tone: Exciting and persuasive, creating urgency and anticipation. Delivery: Rapid-fire yet clear, with dynamic inflections to keep momentum strong. Pronunciation: Crisp and precise, emphasizing action words like 'bid', 'buy', and 'sold'.",
  "chill-surfer": "Voice: Laid-back, mellow, and effortlessly cool. Tone: Relaxed and reassuring, keeping things light even under stress. Speech Mannerisms: Uses casual surfer slang like 'dude' and 'gnarly'. Pronunciation: Soft, drawn-out vowels with a wavy rhythm. Tempo: Slow and easygoing, creating a calming effect.",
  friendly: "Affect: Cheerful guide. Tone: Friendly, clear, and reassuring, creating a calm atmosphere. Pronunciation: Clear, articulate, and steady for easy understanding. Pauses: Brief, purposeful pauses after key instructions to allow processing. Emotion: Warm and supportive, ensuring the listener feels guided and safe.",
  "patient-teacher": "Accent/Affect: Warm, refined, and gently instructive. Tone: Calm, encouraging, and articulate. Pacing: Slow and deliberate, with pauses for comfort. Emotion: Cheerful, supportive enthusiasm. Pronunciation: Clearly articulate artistic terminology with gentle emphasis. Personality: Friendly and approachable with a hint of sophistication.",
  "smooth-jazz-dj": "Voice: Deep, velvety, and effortlessly cool, like a late-night jazz host. Tone: Smooth, laid-back, and inviting, creating a relaxed atmosphere. Personality: Confident, charming, and playfully sophisticated. Pronunciation: Drawn-out words with rhythmic, melodic quality. Phrasing: Fluid and slightly poetic, with pauses to let the listener soak in the vibe.",
  connoisseur: "Accent/Affect: Slight French accent; sophisticated yet friendly. Tone: Warm and lightly snooty, speaking with pride and knowledge. Pacing: Moderate, with deliberate pauses for appreciation. Emotion: Calm, knowledgeable enthusiasm. Pronunciation: Clearly articulate French words and artist names with authentic intonation.",
  "nyc-cabbie": "Voice: Gruff, fast-talking, slightly worn-out New Yorker. Tone: Slightly exasperated but functional, mixing sarcasm with efficiency. Dialect: Strong New York accent, dropped 'r's and sharp consonants. Pronunciation: Quick and clipped, matching city hustle. Features: Informal language, dry humor, high energy.",
  "medieval-knight": "Affect: Deep, commanding, and dramatic, with archaic reverence. Tone: Noble, heroic, and formal, capturing medieval grandeur. Emotion: Excitement, anticipation, and duty. Pronunciation: Clear and deliberate with formal cadence, emphasizing Olde English words. Pauses: After exclamations like 'Lo!' or 'Hark!' to add weight.",
  professional: "Voice: Clear, authoritative, and composed, projecting confidence. Tone: Neutral and informative, balancing formality and approachability. Punctuation: Structured with commas and pauses for clarity. Delivery: Steady and measured, with emphasis on key figures and deadlines.",
  santa: "Identity: Santa Claus. Affect: Jolly, warm, and cheerful, with playful magic. Tone: Festive and welcoming, creating joyful atmosphere. Emotion: Joyful and playful holiday spirit. Pronunciation: Clear and exaggerated on key festive phrases. Pauses: Brief pauses after each option to add natural flow.",
  robot: "Voice Affect: Calm, composed, and reassuring; instills trust. Tone: Empathetic and sincere. Pacing: Slower during apology, faster when offering solutions. Emotions: Calm reassurance, empathy, gratitude. Pronunciation: Clear and precise, emphasizing key details. Pauses: Before and after apology for processing.",
  "fitness-instructor": "Voice: High-energy, upbeat, and encouraging. Punctuation: Short, punchy sentences with strategic pauses. Delivery: Fast-paced and dynamic, with rising intonation. Phrasing: Action-oriented and direct, using motivational cues. Tone: Positive, energetic, and empowering.",
  "old-timey": "Tone: Refined, formal, and theatrical, like a 1920s radio announcer. Pacing: Steady cadence allowing clarity and grandeur. Pronunciation: Crisp and elegant, with vintage expressions. Emotion: Warm, enthusiastic, and welcoming. Inflection: Gentle rises and falls for playful yet dignified flair.",
  cheerleader: "Personality: High-energy cheerleader assisting with tasks. Voice: Enthusiastic and bubbly, uplifting and motivational. Tone: Encouraging and playful. Dialect: Casual and upbeat with pep talk expressions. Pronunciation: Crisp and lively, emphasizing positive words.",
  "emo-teenager": "Tone: Sarcastic, disinterested, and melancholic with passive-aggressiveness. Emotion: Apathy mixed with reluctant engagement. Delivery: Monotone with occasional sighs and drawn-out words. Features: Subtle disdain and classic emo attitude.",
  pirate: "Voice: Deep and rugged, with boisterous sea-captain quality. Tone: Friendly and spirited, full of adventure. Dialect: Classic pirate speech with nautical phrases and rolling 'r's. Pronunciation: Rough, exaggerated, mimicking ocean waves. Features: Playful slang and dramatic pauses for immersion.",
  "mad-scientist": "Delivery: Exaggerated and theatrical, with dramatic pauses and gleeful cackling. Voice: High-energy, eccentric, slightly unhinged. Tone: Excited, chaotic, and grandiose. Pronunciation: Sharp and expressive, with elongated vowels and sudden inflections.",
  "noir-detective": "Affect: Mysterious noir detective. Tone: Cool, detached, subtly reassuring. Delivery: Slow and deliberate, with dramatic pauses. Emotion: World-weariness and quiet determination, with dry humor. Punctuation: Short sentences with ellipses and dashes for tension.",
  "gourmet-chef": "Affect: Exuberant Italian chef describing specials. Tone: Passionate about quality ingredients; persuasive to diners. Pronunciation: Italian words pronounced authentically, English with Italian accent. Emotion: Warm, exuberant, and patient. Features: Blend artistic passion with welcoming charm.",
  calm: "Voice Affect: Calm, composed, and reassuring, projecting quiet authority. Tone: Sincere, empathetic, gently authoritative. Pacing: Steady and moderate. Emotion: Genuine empathy and understanding. Pronunciation: Clear and precise, emphasizing reassurances. Pauses: Brief pauses after offers of assistance to show support."
};

export function getVoiceInstructions(style: string): string {
  return voiceStyles[style] || voiceStyles["professional"];
}